[package]
name = "BlobSafeAccess"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
blobsafe_addr = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "ea05dac18f5cbf79a4b83bbbacb2690657f0198b" }
